CREATE SEQUENCE board_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE board_image (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    board_id NUMBER NOT NULL,
    image_path VARCHAR2(500) NOT NULL,
    original_name VARCHAR2(255),
    upload_date DATE DEFAULT SYSDATE,
    
    CONSTRAINT fk_board_image_board
        FOREIGN KEY (board_id)
        REFERENCES INI_BOARD(BOARD_ID)
        ON DELETE CASCADE
);

DESC board_image;

DROP TABLE board_image;

CREATE SEQUENCE board_image_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
SELECT * FROM board_image;

SELECT user FROM dual;
